// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.9
// source: proto/service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorType int32

const (
	ErrorType_OK                    ErrorType = 0
	ErrorType_WRONG_LEADER          ErrorType = 1
	ErrorType_KEY_NOT_EXIST         ErrorType = 2
	ErrorType_WRONG_VERSION         ErrorType = 3
	ErrorType_INTERNAL_ERROR        ErrorType = 4
	ErrorType_COMPACT_ERROR         ErrorType = 5
	ErrorType_INVALID_ARGUMENT      ErrorType = 6
	ErrorType_MEMBER_ALREADY_EXISTS ErrorType = 7
	ErrorType_MEMBER_NOT_FOUND      ErrorType = 8
	ErrorType_TIMEOUT               ErrorType = 9
	ErrorType_LEASE_NO_EXIST        ErrorType = 10
	ErrorType_LOCK_EXIST            ErrorType = 11
)

// Enum value maps for ErrorType.
var (
	ErrorType_name = map[int32]string{
		0:  "OK",
		1:  "WRONG_LEADER",
		2:  "KEY_NOT_EXIST",
		3:  "WRONG_VERSION",
		4:  "INTERNAL_ERROR",
		5:  "COMPACT_ERROR",
		6:  "INVALID_ARGUMENT",
		7:  "MEMBER_ALREADY_EXISTS",
		8:  "MEMBER_NOT_FOUND",
		9:  "TIMEOUT",
		10: "LEASE_NO_EXIST",
		11: "LOCK_EXIST",
	}
	ErrorType_value = map[string]int32{
		"OK":                    0,
		"WRONG_LEADER":          1,
		"KEY_NOT_EXIST":         2,
		"WRONG_VERSION":         3,
		"INTERNAL_ERROR":        4,
		"COMPACT_ERROR":         5,
		"INVALID_ARGUMENT":      6,
		"MEMBER_ALREADY_EXISTS": 7,
		"MEMBER_NOT_FOUND":      8,
		"TIMEOUT":               9,
		"LEASE_NO_EXIST":        10,
		"LOCK_EXIST":            11,
	}
)

func (x ErrorType) Enum() *ErrorType {
	p := new(ErrorType)
	*p = x
	return p
}

func (x ErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_service_proto_enumTypes[0].Descriptor()
}

func (ErrorType) Type() protoreflect.EnumType {
	return &file_proto_service_proto_enumTypes[0]
}

func (x ErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorType.Descriptor instead.
func (ErrorType) EnumDescriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{0}
}

type CompareType int32

const (
	CompareType_LESS      CompareType = 0
	CompareType_GREATER   CompareType = 1
	CompareType_EQUAL     CompareType = 2
	CompareType_NOT_EQUAL CompareType = 3
)

// Enum value maps for CompareType.
var (
	CompareType_name = map[int32]string{
		0: "LESS",
		1: "GREATER",
		2: "EQUAL",
		3: "NOT_EQUAL",
	}
	CompareType_value = map[string]int32{
		"LESS":      0,
		"GREATER":   1,
		"EQUAL":     2,
		"NOT_EQUAL": 3,
	}
)

func (x CompareType) Enum() *CompareType {
	p := new(CompareType)
	*p = x
	return p
}

func (x CompareType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompareType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_service_proto_enumTypes[1].Descriptor()
}

func (CompareType) Type() protoreflect.EnumType {
	return &file_proto_service_proto_enumTypes[1]
}

func (x CompareType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompareType.Descriptor instead.
func (CompareType) EnumDescriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{1}
}

type Compare struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	CompareType   CompareType            `protobuf:"varint,2,opt,name=compare_type,json=compareType,proto3,enum=proto.CompareType" json:"compare_type,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"` //比较目标version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Compare) Reset() {
	*x = Compare{}
	mi := &file_proto_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Compare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Compare) ProtoMessage() {}

func (x *Compare) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Compare.ProtoReflect.Descriptor instead.
func (*Compare) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{0}
}

func (x *Compare) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Compare) GetCompareType() CompareType {
	if x != nil {
		return x.CompareType
	}
	return CompareType_LESS
}

func (x *Compare) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// txn事务请求
type TxnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Compare       []*Compare             `protobuf:"bytes,1,rep,name=compare,proto3" json:"compare,omitempty"`
	Success       []*Entry               `protobuf:"bytes,2,rep,name=success,proto3" json:"success,omitempty"` //compare全过执行
	Failed        []*Entry               `protobuf:"bytes,3,rep,name=failed,proto3" json:"failed,omitempty"`   //compatre失败执行
	ClientId      int64                  `protobuf:"varint,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RequestId     int64                  `protobuf:"varint,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxnRequest) Reset() {
	*x = TxnRequest{}
	mi := &file_proto_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnRequest) ProtoMessage() {}

func (x *TxnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnRequest.ProtoReflect.Descriptor instead.
func (*TxnRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{1}
}

func (x *TxnRequest) GetCompare() []*Compare {
	if x != nil {
		return x.Compare
	}
	return nil
}

func (x *TxnRequest) GetSuccess() []*Entry {
	if x != nil {
		return x.Success
	}
	return nil
}

func (x *TxnRequest) GetFailed() []*Entry {
	if x != nil {
		return x.Failed
	}
	return nil
}

func (x *TxnRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *TxnRequest) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type TxnReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         ErrorType              `protobuf:"varint,1,opt,name=error,proto3,enum=proto.ErrorType" json:"error,omitempty"`
	Results       []*KeyValue            `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	LeaderId      int64                  `protobuf:"varint,3,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	Succeeded     bool                   `protobuf:"varint,4,opt,name=succeeded,proto3" json:"succeeded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxnReply) Reset() {
	*x = TxnReply{}
	mi := &file_proto_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnReply) ProtoMessage() {}

func (x *TxnReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnReply.ProtoReflect.Descriptor instead.
func (*TxnReply) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{2}
}

func (x *TxnReply) GetError() ErrorType {
	if x != nil {
		return x.Error
	}
	return ErrorType_OK
}

func (x *TxnReply) GetResults() []*KeyValue {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *TxnReply) GetLeaderId() int64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *TxnReply) GetSucceeded() bool {
	if x != nil {
		return x.Succeeded
	}
	return false
}

// 分布式锁
type LockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	LeaseId       int64                  `protobuf:"varint,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	ClientId      int64                  `protobuf:"varint,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RequestId     int64                  `protobuf:"varint,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockRequest) Reset() {
	*x = LockRequest{}
	mi := &file_proto_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockRequest) ProtoMessage() {}

func (x *LockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockRequest.ProtoReflect.Descriptor instead.
func (*LockRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{3}
}

func (x *LockRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LockRequest) GetLeaseId() int64 {
	if x != nil {
		return x.LeaseId
	}
	return 0
}

func (x *LockRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *LockRequest) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type LockReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Revision      int64                  `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Error         ErrorType              `protobuf:"varint,3,opt,name=error,proto3,enum=proto.ErrorType" json:"error,omitempty"`
	LeaderId      int64                  `protobuf:"varint,4,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockReply) Reset() {
	*x = LockReply{}
	mi := &file_proto_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockReply) ProtoMessage() {}

func (x *LockReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockReply.ProtoReflect.Descriptor instead.
func (*LockReply) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{4}
}

func (x *LockReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LockReply) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *LockReply) GetError() ErrorType {
	if x != nil {
		return x.Error
	}
	return ErrorType_OK
}

func (x *LockReply) GetLeaderId() int64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

// 释放锁
type UnlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockKey       string                 `protobuf:"bytes,1,opt,name=lock_key,json=lockKey,proto3" json:"lock_key,omitempty"` // Lock 生成的内部 key（/lock/<key>/<client>-<request>）
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`               // LockReply.revision，CAS 校验
	ClientId      int64                  `protobuf:"varint,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RequestId     int64                  `protobuf:"varint,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockRequest) Reset() {
	*x = UnlockRequest{}
	mi := &file_proto_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockRequest) ProtoMessage() {}

func (x *UnlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockRequest.ProtoReflect.Descriptor instead.
func (*UnlockRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{5}
}

func (x *UnlockRequest) GetLockKey() string {
	if x != nil {
		return x.LockKey
	}
	return ""
}

func (x *UnlockRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *UnlockRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *UnlockRequest) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type UnlockReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         ErrorType              `protobuf:"varint,2,opt,name=error,proto3,enum=proto.ErrorType" json:"error,omitempty"`
	LeaderId      int64                  `protobuf:"varint,3,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockReply) Reset() {
	*x = UnlockReply{}
	mi := &file_proto_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockReply) ProtoMessage() {}

func (x *UnlockReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockReply.ProtoReflect.Descriptor instead.
func (*UnlockReply) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{6}
}

func (x *UnlockReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnlockReply) GetError() ErrorType {
	if x != nil {
		return x.Error
	}
	return ErrorType_OK
}

func (x *UnlockReply) GetLeaderId() int64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

// watch请求
type WatchRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Key            string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	StartReversion int64                  `protobuf:"varint,2,opt,name=start_reversion,json=startReversion,proto3" json:"start_reversion,omitempty"` //从哪个版本开始watch
	Prefix         bool                   `protobuf:"varint,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_proto_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{7}
}

func (x *WatchRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WatchRequest) GetStartReversion() int64 {
	if x != nil {
		return x.StartReversion
	}
	return 0
}

func (x *WatchRequest) GetPrefix() bool {
	if x != nil {
		return x.Prefix
	}
	return false
}

// watch回复
type WatchReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Revision      int64                  `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Err           ErrorType              `protobuf:"varint,5,opt,name=err,proto3,enum=proto.ErrorType" json:"err,omitempty"`
	LeaderId      int64                  `protobuf:"varint,6,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchReply) Reset() {
	*x = WatchReply{}
	mi := &file_proto_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchReply) ProtoMessage() {}

func (x *WatchReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchReply.ProtoReflect.Descriptor instead.
func (*WatchReply) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{8}
}

func (x *WatchReply) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WatchReply) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *WatchReply) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *WatchReply) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WatchReply) GetErr() ErrorType {
	if x != nil {
		return x.Err
	}
	return ErrorType_OK
}

func (x *WatchReply) GetLeaderId() int64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

// put请求
type PutRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Key             string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value           string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	RequestId       int64                  `protobuf:"varint,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ClientId        int64                  `protobuf:"varint,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,5,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	ExpireAt        int64                  `protobuf:"varint,6,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"` //TTL 秒数，自动创建 lease 并绑定
	LeaseId         int64                  `protobuf:"varint,7,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`    //绑定到已有 lease，优先级高于 expire_at
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_proto_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{9}
}

func (x *PutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *PutRequest) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *PutRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *PutRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

func (x *PutRequest) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

func (x *PutRequest) GetLeaseId() int64 {
	if x != nil {
		return x.LeaseId
	}
	return 0
}

// put回复
type PutReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         ErrorType              `protobuf:"varint,1,opt,name=error,proto3,enum=proto.ErrorType" json:"error,omitempty"`
	LeaderId      int64                  `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutReply) Reset() {
	*x = PutReply{}
	mi := &file_proto_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutReply) ProtoMessage() {}

func (x *PutReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutReply.ProtoReflect.Descriptor instead.
func (*PutReply) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{10}
}

func (x *PutReply) GetError() ErrorType {
	if x != nil {
		return x.Error
	}
	return ErrorType_OK
}

func (x *PutReply) GetLeaderId() int64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *PutReply) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	RequestId     int64                  `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ClientId      int64                  `protobuf:"varint,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Prefix        bool                   `protobuf:"varint,5,opt,name=prefix,proto3" json:"prefix,omitempty"` //是否按前缀查询
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetRequest) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *GetRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *GetRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetRequest) GetPrefix() bool {
	if x != nil {
		return x.Prefix
	}
	return false
}

type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_proto_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{12}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *KeyValue) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kvs           []*KeyValue            `protobuf:"bytes,1,rep,name=kvs,proto3" json:"kvs,omitempty"`
	Error         ErrorType              `protobuf:"varint,2,opt,name=error,proto3,enum=proto.ErrorType" json:"error,omitempty"`
	LeaderId      int64                  `protobuf:"varint,3,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=Version,proto3" json:"Version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReply) Reset() {
	*x = GetReply{}
	mi := &file_proto_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReply) ProtoMessage() {}

func (x *GetReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReply.ProtoReflect.Descriptor instead.
func (*GetReply) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetReply) GetKvs() []*KeyValue {
	if x != nil {
		return x.Kvs
	}
	return nil
}

func (x *GetReply) GetError() ErrorType {
	if x != nil {
		return x.Error
	}
	return ErrorType_OK
}

func (x *GetReply) GetLeaderId() int64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *GetReply) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// 删除请求
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	RequestId     int64                  `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ClientId      int64                  `protobuf:"varint,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteRequest) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *DeleteRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type DeleteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         ErrorType              `protobuf:"varint,1,opt,name=error,proto3,enum=proto.ErrorType" json:"error,omitempty"`
	LeaderId      int64                  `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReply) Reset() {
	*x = DeleteReply{}
	mi := &file_proto_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReply) ProtoMessage() {}

func (x *DeleteReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReply.ProtoReflect.Descriptor instead.
func (*DeleteReply) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteReply) GetError() ErrorType {
	if x != nil {
		return x.Error
	}
	return ErrorType_OK
}

func (x *DeleteReply) GetLeaderId() int64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *DeleteReply) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// compact请求
type CompactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      int64                  `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"` //compact到这个版本
	ClientId      int64                  `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RequestId     int64                  `protobuf:"varint,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactRequest) Reset() {
	*x = CompactRequest{}
	mi := &file_proto_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactRequest) ProtoMessage() {}

func (x *CompactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactRequest.ProtoReflect.Descriptor instead.
func (*CompactRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{16}
}

func (x *CompactRequest) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *CompactRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *CompactRequest) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type CompactReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         ErrorType              `protobuf:"varint,1,opt,name=error,proto3,enum=proto.ErrorType" json:"error,omitempty"`
	LeaderId      int64                  `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactReply) Reset() {
	*x = CompactReply{}
	mi := &file_proto_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactReply) ProtoMessage() {}

func (x *CompactReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactReply.ProtoReflect.Descriptor instead.
func (*CompactReply) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{17}
}

func (x *CompactReply) GetError() ErrorType {
	if x != nil {
		return x.Error
	}
	return ErrorType_OK
}

func (x *CompactReply) GetLeaderId() int64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

// keepalive请求
type KeepAliveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepAliveRequest) Reset() {
	*x = KeepAliveRequest{}
	mi := &file_proto_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepAliveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepAliveRequest) ProtoMessage() {}

func (x *KeepAliveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepAliveRequest.ProtoReflect.Descriptor instead.
func (*KeepAliveRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{18}
}

func (x *KeepAliveRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// keepalive回复
type KeepAliveReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         ErrorType              `protobuf:"varint,1,opt,name=error,proto3,enum=proto.ErrorType" json:"error,omitempty"`
	LeaderId      int64                  `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepAliveReply) Reset() {
	*x = KeepAliveReply{}
	mi := &file_proto_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepAliveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepAliveReply) ProtoMessage() {}

func (x *KeepAliveReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepAliveReply.ProtoReflect.Descriptor instead.
func (*KeepAliveReply) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{19}
}

func (x *KeepAliveReply) GetError() ErrorType {
	if x != nil {
		return x.Error
	}
	return ErrorType_OK
}

func (x *KeepAliveReply) GetLeaderId() int64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

// 创建 lease
type GrantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ttl           int64                  `protobuf:"varint,1,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantRequest) Reset() {
	*x = GrantRequest{}
	mi := &file_proto_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantRequest) ProtoMessage() {}

func (x *GrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantRequest.ProtoReflect.Descriptor instead.
func (*GrantRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{20}
}

func (x *GrantRequest) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type GrantReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         ErrorType              `protobuf:"varint,1,opt,name=error,proto3,enum=proto.ErrorType" json:"error,omitempty"`
	LeaderId      int64                  `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	LeaseId       int64                  `protobuf:"varint,3,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantReply) Reset() {
	*x = GrantReply{}
	mi := &file_proto_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantReply) ProtoMessage() {}

func (x *GrantReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantReply.ProtoReflect.Descriptor instead.
func (*GrantReply) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{21}
}

func (x *GrantReply) GetError() ErrorType {
	if x != nil {
		return x.Error
	}
	return ErrorType_OK
}

func (x *GrantReply) GetLeaderId() int64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *GrantReply) GetLeaseId() int64 {
	if x != nil {
		return x.LeaseId
	}
	return 0
}

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	ExpireAt      int64                  `protobuf:"varint,4,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"` //过期时间
	LeaseId       int64                  `protobuf:"varint,5,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_proto_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{22}
}

func (x *Entry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Entry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Entry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Entry) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

func (x *Entry) GetLeaseId() int64 {
	if x != nil {
		return x.LeaseId
	}
	return 0
}

// 客户端批量提交
type BatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Entry               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	ClientId      int64                  `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RequestId     int64                  `protobuf:"varint,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRequest) Reset() {
	*x = BatchRequest{}
	mi := &file_proto_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequest) ProtoMessage() {}

func (x *BatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRequest.ProtoReflect.Descriptor instead.
func (*BatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{23}
}

func (x *BatchRequest) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *BatchRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *BatchRequest) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type BatchReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         ErrorType              `protobuf:"varint,2,opt,name=error,proto3,enum=proto.ErrorType" json:"error,omitempty"`
	LeaderId      int64                  `protobuf:"varint,3,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchReply) Reset() {
	*x = BatchReply{}
	mi := &file_proto_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchReply) ProtoMessage() {}

func (x *BatchReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchReply.ProtoReflect.Descriptor instead.
func (*BatchReply) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{24}
}

func (x *BatchReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BatchReply) GetError() ErrorType {
	if x != nil {
		return x.Error
	}
	return ErrorType_OK
}

func (x *BatchReply) GetLeaderId() int64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

// 添加集群成员
type AddMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberRequest) Reset() {
	*x = AddMemberRequest{}
	mi := &file_proto_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberRequest) ProtoMessage() {}

func (x *AddMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberRequest.ProtoReflect.Descriptor instead.
func (*AddMemberRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{25}
}

func (x *AddMemberRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddMemberRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type AddMemberReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         ErrorType              `protobuf:"varint,1,opt,name=error,proto3,enum=proto.ErrorType" json:"error,omitempty"`
	LeaderId      int64                  `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberReply) Reset() {
	*x = AddMemberReply{}
	mi := &file_proto_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberReply) ProtoMessage() {}

func (x *AddMemberReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberReply.ProtoReflect.Descriptor instead.
func (*AddMemberReply) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{26}
}

func (x *AddMemberReply) GetError() ErrorType {
	if x != nil {
		return x.Error
	}
	return ErrorType_OK
}

func (x *AddMemberReply) GetLeaderId() int64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

type Memberchange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Memberchange) Reset() {
	*x = Memberchange{}
	mi := &file_proto_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Memberchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Memberchange) ProtoMessage() {}

func (x *Memberchange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Memberchange.ProtoReflect.Descriptor instead.
func (*Memberchange) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{27}
}

func (x *Memberchange) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Memberchange) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Memberchange) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// 移除集群成员
type DeleteMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMemberRequest) Reset() {
	*x = DeleteMemberRequest{}
	mi := &file_proto_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemberRequest) ProtoMessage() {}

func (x *DeleteMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemberRequest.ProtoReflect.Descriptor instead.
func (*DeleteMemberRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteMemberRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteMemberRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type DeleteMemberReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         ErrorType              `protobuf:"varint,1,opt,name=error,proto3,enum=proto.ErrorType" json:"error,omitempty"`
	LeaderId      int64                  `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMemberReply) Reset() {
	*x = DeleteMemberReply{}
	mi := &file_proto_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMemberReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemberReply) ProtoMessage() {}

func (x *DeleteMemberReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemberReply.ProtoReflect.Descriptor instead.
func (*DeleteMemberReply) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{29}
}

func (x *DeleteMemberReply) GetError() ErrorType {
	if x != nil {
		return x.Error
	}
	return ErrorType_OK
}

func (x *DeleteMemberReply) GetLeaderId() int64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

type RequestVoteArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	CandidateId   int32                  `protobuf:"varint,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	LastLogIndex  int32                  `protobuf:"varint,3,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	LastLogTerm   int32                  `protobuf:"varint,4,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteArgs) Reset() {
	*x = RequestVoteArgs{}
	mi := &file_proto_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteArgs) ProtoMessage() {}

func (x *RequestVoteArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteArgs.ProtoReflect.Descriptor instead.
func (*RequestVoteArgs) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{30}
}

func (x *RequestVoteArgs) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteArgs) GetCandidateId() int32 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

func (x *RequestVoteArgs) GetLastLogIndex() int32 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *RequestVoteArgs) GetLastLogTerm() int32 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

type RequestVoteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted   bool                   `protobuf:"varint,2,opt,name=vote_granted,json=voteGranted,proto3" json:"vote_granted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteReply) Reset() {
	*x = RequestVoteReply{}
	mi := &file_proto_service_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteReply) ProtoMessage() {}

func (x *RequestVoteReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteReply.ProtoReflect.Descriptor instead.
func (*RequestVoteReply) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{31}
}

func (x *RequestVoteReply) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteReply) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Command       []byte                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_service_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{32}
}

func (x *LogEntry) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *LogEntry) GetCommand() []byte {
	if x != nil {
		return x.Command
	}
	return nil
}

type HeartbeatArgs struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LeaderId          int32                  `protobuf:"varint,1,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	LeaderTerm        int32                  `protobuf:"varint,2,opt,name=leader_term,json=leaderTerm,proto3" json:"leader_term,omitempty"`
	PreLogIndex       int32                  `protobuf:"varint,3,opt,name=pre_log_index,json=preLogIndex,proto3" json:"pre_log_index,omitempty"`
	PreLogTerm        int32                  `protobuf:"varint,4,opt,name=pre_log_term,json=preLogTerm,proto3" json:"pre_log_term,omitempty"`
	Entries           []*LogEntry            `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommitIndex int32                  `protobuf:"varint,6,opt,name=leader_commit_index,json=leaderCommitIndex,proto3" json:"leader_commit_index,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeartbeatArgs) Reset() {
	*x = HeartbeatArgs{}
	mi := &file_proto_service_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatArgs) ProtoMessage() {}

func (x *HeartbeatArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatArgs.ProtoReflect.Descriptor instead.
func (*HeartbeatArgs) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{33}
}

func (x *HeartbeatArgs) GetLeaderId() int32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *HeartbeatArgs) GetLeaderTerm() int32 {
	if x != nil {
		return x.LeaderTerm
	}
	return 0
}

func (x *HeartbeatArgs) GetPreLogIndex() int32 {
	if x != nil {
		return x.PreLogIndex
	}
	return 0
}

func (x *HeartbeatArgs) GetPreLogTerm() int32 {
	if x != nil {
		return x.PreLogTerm
	}
	return 0
}

func (x *HeartbeatArgs) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *HeartbeatArgs) GetLeaderCommitIndex() int32 {
	if x != nil {
		return x.LeaderCommitIndex
	}
	return 0
}

type HeartbeatReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Term          int32                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	ConflictIndex int32                  `protobuf:"varint,3,opt,name=conflict_index,json=conflictIndex,proto3" json:"conflict_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatReply) Reset() {
	*x = HeartbeatReply{}
	mi := &file_proto_service_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReply) ProtoMessage() {}

func (x *HeartbeatReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReply.ProtoReflect.Descriptor instead.
func (*HeartbeatReply) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{34}
}

func (x *HeartbeatReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatReply) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *HeartbeatReply) GetConflictIndex() int32 {
	if x != nil {
		return x.ConflictIndex
	}
	return 0
}

type InstallSnapshotArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId      int32                  `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	LastSnapIndex int32                  `protobuf:"varint,3,opt,name=last_snap_index,json=lastSnapIndex,proto3" json:"last_snap_index,omitempty"`
	LastSnapTerm  int32                  `protobuf:"varint,4,opt,name=last_snap_term,json=lastSnapTerm,proto3" json:"last_snap_term,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallSnapshotArgs) Reset() {
	*x = InstallSnapshotArgs{}
	mi := &file_proto_service_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSnapshotArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSnapshotArgs) ProtoMessage() {}

func (x *InstallSnapshotArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSnapshotArgs.ProtoReflect.Descriptor instead.
func (*InstallSnapshotArgs) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{35}
}

func (x *InstallSnapshotArgs) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *InstallSnapshotArgs) GetLeaderId() int32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *InstallSnapshotArgs) GetLastSnapIndex() int32 {
	if x != nil {
		return x.LastSnapIndex
	}
	return 0
}

func (x *InstallSnapshotArgs) GetLastSnapTerm() int32 {
	if x != nil {
		return x.LastSnapTerm
	}
	return 0
}

func (x *InstallSnapshotArgs) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type InstallSnapshotReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallSnapshotReply) Reset() {
	*x = InstallSnapshotReply{}
	mi := &file_proto_service_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSnapshotReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSnapshotReply) ProtoMessage() {}

func (x *InstallSnapshotReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSnapshotReply.ProtoReflect.Descriptor instead.
func (*InstallSnapshotReply) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{36}
}

func (x *InstallSnapshotReply) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

type Op struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Type            string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Key             string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value           string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	ClientId        int64                  `protobuf:"varint,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RequestId       int64                  `protobuf:"varint,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,6,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	ExpireAt        int64                  `protobuf:"varint,7,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	// batch
	Entries []*Entry `protobuf:"bytes,8,rep,name=entries,proto3" json:"entries,omitempty"`
	// lease
	LeaseId int64 `protobuf:"varint,9,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	// member_change
	MemberChange *Memberchange `protobuf:"bytes,10,opt,name=member_change,json=memberChange,proto3" json:"member_change,omitempty"`
	// txn
	Compares       []*Compare `protobuf:"bytes,11,rep,name=compares,proto3" json:"compares,omitempty"`
	SuccessEntries []*Entry   `protobuf:"bytes,12,rep,name=success_entries,json=successEntries,proto3" json:"success_entries,omitempty"`
	FailedEntries  []*Entry   `protobuf:"bytes,13,rep,name=failed_entries,json=failedEntries,proto3" json:"failed_entries,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Op) Reset() {
	*x = Op{}
	mi := &file_proto_service_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Op) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Op) ProtoMessage() {}

func (x *Op) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Op.ProtoReflect.Descriptor instead.
func (*Op) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{37}
}

func (x *Op) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Op) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Op) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Op) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *Op) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *Op) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

func (x *Op) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

func (x *Op) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *Op) GetLeaseId() int64 {
	if x != nil {
		return x.LeaseId
	}
	return 0
}

func (x *Op) GetMemberChange() *Memberchange {
	if x != nil {
		return x.MemberChange
	}
	return nil
}

func (x *Op) GetCompares() []*Compare {
	if x != nil {
		return x.Compares
	}
	return nil
}

func (x *Op) GetSuccessEntries() []*Entry {
	if x != nil {
		return x.SuccessEntries
	}
	return nil
}

func (x *Op) GetFailedEntries() []*Entry {
	if x != nil {
		return x.FailedEntries
	}
	return nil
}

var File_proto_service_proto protoreflect.FileDescriptor

const file_proto_service_proto_rawDesc = "" +
	"\n" +
	"\x13proto/service.proto\x12\x05proto\"l\n" +
	"\aCompare\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\fcompare_type\x18\x02 \x01(\x0e2\x12.proto.CompareTypeR\vcompareType\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\"\xc0\x01\n" +
	"\n" +
	"TxnRequest\x12(\n" +
	"\acompare\x18\x01 \x03(\v2\x0e.proto.CompareR\acompare\x12&\n" +
	"\asuccess\x18\x02 \x03(\v2\f.proto.EntryR\asuccess\x12$\n" +
	"\x06failed\x18\x03 \x03(\v2\f.proto.EntryR\x06failed\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\x03R\bclientId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\x03R\trequestId\"\x98\x01\n" +
	"\bTxnReply\x12&\n" +
	"\x05error\x18\x01 \x01(\x0e2\x10.proto.ErrorTypeR\x05error\x12)\n" +
	"\aresults\x18\x02 \x03(\v2\x0f.proto.KeyValueR\aresults\x12\x1b\n" +
	"\tleader_id\x18\x03 \x01(\x03R\bleaderId\x12\x1c\n" +
	"\tsucceeded\x18\x04 \x01(\bR\tsucceeded\"v\n" +
	"\vLockRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\x03R\aleaseId\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\x03R\bclientId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\x03R\trequestId\"\x86\x01\n" +
	"\tLockReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x03R\brevision\x12&\n" +
	"\x05error\x18\x03 \x01(\x0e2\x10.proto.ErrorTypeR\x05error\x12\x1b\n" +
	"\tleader_id\x18\x04 \x01(\x03R\bleaderId\"\x80\x01\n" +
	"\rUnlockRequest\x12\x19\n" +
	"\block_key\x18\x01 \x01(\tR\alockKey\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\x03R\bclientId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\x03R\trequestId\"l\n" +
	"\vUnlockReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12&\n" +
	"\x05error\x18\x02 \x01(\x0e2\x10.proto.ErrorTypeR\x05error\x12\x1b\n" +
	"\tleader_id\x18\x03 \x01(\x03R\bleaderId\"a\n" +
	"\fWatchRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x0fstart_reversion\x18\x02 \x01(\x03R\x0estartReversion\x12\x16\n" +
	"\x06prefix\x18\x03 \x01(\bR\x06prefix\"\xa5\x01\n" +
	"\n" +
	"WatchReply\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x03R\brevision\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\"\n" +
	"\x03err\x18\x05 \x01(\x0e2\x10.proto.ErrorTypeR\x03err\x12\x1b\n" +
	"\tleader_id\x18\x06 \x01(\x03R\bleaderId\"\xd3\x01\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\x03R\trequestId\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\x03R\bclientId\x12)\n" +
	"\x10expected_version\x18\x05 \x01(\x03R\x0fexpectedVersion\x12\x1b\n" +
	"\texpire_at\x18\x06 \x01(\x03R\bexpireAt\x12\x19\n" +
	"\blease_id\x18\a \x01(\x03R\aleaseId\"i\n" +
	"\bPutReply\x12&\n" +
	"\x05error\x18\x01 \x01(\x0e2\x10.proto.ErrorTypeR\x05error\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\x03R\bleaderId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\"\x8c\x01\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\x03R\trequestId\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\x03R\bclientId\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x12\x16\n" +
	"\x06prefix\x18\x05 \x01(\bR\x06prefix\"L\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\"\x8c\x01\n" +
	"\bGetReply\x12!\n" +
	"\x03kvs\x18\x01 \x03(\v2\x0f.proto.KeyValueR\x03kvs\x12&\n" +
	"\x05error\x18\x02 \x01(\x0e2\x10.proto.ErrorTypeR\x05error\x12\x1b\n" +
	"\tleader_id\x18\x03 \x01(\x03R\bleaderId\x12\x18\n" +
	"\aVersion\x18\x04 \x01(\x03R\aVersion\"]\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\x03R\trequestId\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\x03R\bclientId\"l\n" +
	"\vDeleteReply\x12&\n" +
	"\x05error\x18\x01 \x01(\x0e2\x10.proto.ErrorTypeR\x05error\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\x03R\bleaderId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\"h\n" +
	"\x0eCompactRequest\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x03R\brevision\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x03R\bclientId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\x03R\trequestId\"S\n" +
	"\fCompactReply\x12&\n" +
	"\x05error\x18\x01 \x01(\x0e2\x10.proto.ErrorTypeR\x05error\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\x03R\bleaderId\"$\n" +
	"\x10KeepAliveRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"U\n" +
	"\x0eKeepAliveReply\x12&\n" +
	"\x05error\x18\x01 \x01(\x0e2\x10.proto.ErrorTypeR\x05error\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\x03R\bleaderId\" \n" +
	"\fGrantRequest\x12\x10\n" +
	"\x03ttl\x18\x01 \x01(\x03R\x03ttl\"l\n" +
	"\n" +
	"GrantReply\x12&\n" +
	"\x05error\x18\x01 \x01(\x0e2\x10.proto.ErrorTypeR\x05error\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\x03R\bleaderId\x12\x19\n" +
	"\blease_id\x18\x03 \x01(\x03R\aleaseId\"{\n" +
	"\x05Entry\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x1b\n" +
	"\texpire_at\x18\x04 \x01(\x03R\bexpireAt\x12\x19\n" +
	"\blease_id\x18\x05 \x01(\x03R\aleaseId\"r\n" +
	"\fBatchRequest\x12&\n" +
	"\aentries\x18\x01 \x03(\v2\f.proto.EntryR\aentries\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x03R\bclientId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\x03R\trequestId\"k\n" +
	"\n" +
	"BatchReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12&\n" +
	"\x05error\x18\x02 \x01(\x0e2\x10.proto.ErrorTypeR\x05error\x12\x1b\n" +
	"\tleader_id\x18\x03 \x01(\x03R\bleaderId\"<\n" +
	"\x10AddMemberRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"U\n" +
	"\x0eAddMemberReply\x12&\n" +
	"\x05error\x18\x01 \x01(\x0e2\x10.proto.ErrorTypeR\x05error\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\x03R\bleaderId\"L\n" +
	"\fMemberchange\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"?\n" +
	"\x13DeleteMemberRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"X\n" +
	"\x11DeleteMemberReply\x12&\n" +
	"\x05error\x18\x01 \x01(\x0e2\x10.proto.ErrorTypeR\x05error\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\x03R\bleaderId\"\x92\x01\n" +
	"\x0fRequestVoteArgs\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\x12!\n" +
	"\fcandidate_id\x18\x02 \x01(\x05R\vcandidateId\x12$\n" +
	"\x0elast_log_index\x18\x03 \x01(\x05R\flastLogIndex\x12\"\n" +
	"\rlast_log_term\x18\x04 \x01(\x05R\vlastLogTerm\"I\n" +
	"\x10RequestVoteReply\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\x12!\n" +
	"\fvote_granted\x18\x02 \x01(\bR\vvoteGranted\"8\n" +
	"\bLogEntry\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x18\n" +
	"\acommand\x18\x02 \x01(\fR\acommand\"\xee\x01\n" +
	"\rHeartbeatArgs\x12\x1b\n" +
	"\tleader_id\x18\x01 \x01(\x05R\bleaderId\x12\x1f\n" +
	"\vleader_term\x18\x02 \x01(\x05R\n" +
	"leaderTerm\x12\"\n" +
	"\rpre_log_index\x18\x03 \x01(\x05R\vpreLogIndex\x12 \n" +
	"\fpre_log_term\x18\x04 \x01(\x05R\n" +
	"preLogTerm\x12)\n" +
	"\aentries\x18\x05 \x03(\v2\x0f.proto.LogEntryR\aentries\x12.\n" +
	"\x13leader_commit_index\x18\x06 \x01(\x05R\x11leaderCommitIndex\"e\n" +
	"\x0eHeartbeatReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x05R\x04term\x12%\n" +
	"\x0econflict_index\x18\x03 \x01(\x05R\rconflictIndex\"\xa8\x01\n" +
	"\x13InstallSnapshotArgs\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\x05R\bleaderId\x12&\n" +
	"\x0flast_snap_index\x18\x03 \x01(\x05R\rlastSnapIndex\x12$\n" +
	"\x0elast_snap_term\x18\x04 \x01(\x05R\flastSnapTerm\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\"*\n" +
	"\x14InstallSnapshotReply\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\"\xd9\x03\n" +
	"\x02Op\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\x03R\bclientId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\x03R\trequestId\x12)\n" +
	"\x10expected_version\x18\x06 \x01(\x03R\x0fexpectedVersion\x12\x1b\n" +
	"\texpire_at\x18\a \x01(\x03R\bexpireAt\x12&\n" +
	"\aentries\x18\b \x03(\v2\f.proto.EntryR\aentries\x12\x19\n" +
	"\blease_id\x18\t \x01(\x03R\aleaseId\x128\n" +
	"\rmember_change\x18\n" +
	" \x01(\v2\x13.proto.MemberchangeR\fmemberChange\x12*\n" +
	"\bcompares\x18\v \x03(\v2\x0e.proto.CompareR\bcompares\x125\n" +
	"\x0fsuccess_entries\x18\f \x03(\v2\f.proto.EntryR\x0esuccessEntries\x123\n" +
	"\x0efailed_entries\x18\r \x03(\v2\f.proto.EntryR\rfailedEntries*\xea\x01\n" +
	"\tErrorType\x12\x06\n" +
	"\x02OK\x10\x00\x12\x10\n" +
	"\fWRONG_LEADER\x10\x01\x12\x11\n" +
	"\rKEY_NOT_EXIST\x10\x02\x12\x11\n" +
	"\rWRONG_VERSION\x10\x03\x12\x12\n" +
	"\x0eINTERNAL_ERROR\x10\x04\x12\x11\n" +
	"\rCOMPACT_ERROR\x10\x05\x12\x14\n" +
	"\x10INVALID_ARGUMENT\x10\x06\x12\x19\n" +
	"\x15MEMBER_ALREADY_EXISTS\x10\a\x12\x14\n" +
	"\x10MEMBER_NOT_FOUND\x10\b\x12\v\n" +
	"\aTIMEOUT\x10\t\x12\x12\n" +
	"\x0eLEASE_NO_EXIST\x10\n" +
	"\x12\x0e\n" +
	"\n" +
	"LOCK_EXIST\x10\v*>\n" +
	"\vCompareType\x12\b\n" +
	"\x04LESS\x10\x00\x12\v\n" +
	"\aGREATER\x10\x01\x12\t\n" +
	"\x05EQUAL\x10\x02\x12\r\n" +
	"\tNOT_EQUAL\x10\x032\xa7\x05\n" +
	"\x02Kv\x12)\n" +
	"\x03Put\x12\x11.proto.PutRequest\x1a\x0f.proto.PutReply\x12)\n" +
	"\x03Get\x12\x11.proto.GetRequest\x1a\x0f.proto.GetReply\x122\n" +
	"\x06Delete\x12\x14.proto.DeleteRequest\x1a\x12.proto.DeleteReply\x12/\n" +
	"\x05Batch\x12\x13.proto.BatchRequest\x1a\x11.proto.BatchReply\x121\n" +
	"\x05Watch\x12\x13.proto.WatchRequest\x1a\x11.proto.WatchReply0\x01\x125\n" +
	"\aCompact\x12\x15.proto.CompactRequest\x1a\x13.proto.CompactReply\x12;\n" +
	"\tKeepAlive\x12\x17.proto.KeepAliveRequest\x1a\x15.proto.KeepAliveReply\x12/\n" +
	"\x05Grant\x12\x13.proto.GrantRequest\x1a\x11.proto.GrantReply\x12;\n" +
	"\tAddMember\x12\x17.proto.AddMemberRequest\x1a\x15.proto.AddMemberReply\x12D\n" +
	"\fDeleteMember\x12\x1a.proto.DeleteMemberRequest\x1a\x18.proto.DeleteMemberReply\x12)\n" +
	"\x03Txn\x12\x11.proto.TxnRequest\x1a\x0f.proto.TxnReply\x12,\n" +
	"\x04Lock\x12\x12.proto.LockRequest\x1a\x10.proto.LockReply\x122\n" +
	"\x06Unlock\x12\x14.proto.UnlockRequest\x1a\x12.proto.UnlockReply2\xd0\x01\n" +
	"\x04Raft\x12>\n" +
	"\vRequestVote\x12\x16.proto.RequestVoteArgs\x1a\x17.proto.RequestVoteReply\x12<\n" +
	"\rAppendEntries\x12\x14.proto.HeartbeatArgs\x1a\x15.proto.HeartbeatReply\x12J\n" +
	"\x0fInstallSnapshot\x12\x1a.proto.InstallSnapshotArgs\x1a\x1b.proto.InstallSnapshotReplyB\x0eZ\f/proto;protob\x06proto3"

var (
	file_proto_service_proto_rawDescOnce sync.Once
	file_proto_service_proto_rawDescData []byte
)

func file_proto_service_proto_rawDescGZIP() []byte {
	file_proto_service_proto_rawDescOnce.Do(func() {
		file_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_service_proto_rawDesc), len(file_proto_service_proto_rawDesc)))
	})
	return file_proto_service_proto_rawDescData
}

var file_proto_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_proto_service_proto_goTypes = []any{
	(ErrorType)(0),               // 0: proto.ErrorType
	(CompareType)(0),             // 1: proto.CompareType
	(*Compare)(nil),              // 2: proto.Compare
	(*TxnRequest)(nil),           // 3: proto.TxnRequest
	(*TxnReply)(nil),             // 4: proto.TxnReply
	(*LockRequest)(nil),          // 5: proto.LockRequest
	(*LockReply)(nil),            // 6: proto.LockReply
	(*UnlockRequest)(nil),        // 7: proto.UnlockRequest
	(*UnlockReply)(nil),          // 8: proto.UnlockReply
	(*WatchRequest)(nil),         // 9: proto.WatchRequest
	(*WatchReply)(nil),           // 10: proto.WatchReply
	(*PutRequest)(nil),           // 11: proto.PutRequest
	(*PutReply)(nil),             // 12: proto.PutReply
	(*GetRequest)(nil),           // 13: proto.GetRequest
	(*KeyValue)(nil),             // 14: proto.KeyValue
	(*GetReply)(nil),             // 15: proto.GetReply
	(*DeleteRequest)(nil),        // 16: proto.DeleteRequest
	(*DeleteReply)(nil),          // 17: proto.DeleteReply
	(*CompactRequest)(nil),       // 18: proto.CompactRequest
	(*CompactReply)(nil),         // 19: proto.CompactReply
	(*KeepAliveRequest)(nil),     // 20: proto.KeepAliveRequest
	(*KeepAliveReply)(nil),       // 21: proto.KeepAliveReply
	(*GrantRequest)(nil),         // 22: proto.GrantRequest
	(*GrantReply)(nil),           // 23: proto.GrantReply
	(*Entry)(nil),                // 24: proto.Entry
	(*BatchRequest)(nil),         // 25: proto.BatchRequest
	(*BatchReply)(nil),           // 26: proto.BatchReply
	(*AddMemberRequest)(nil),     // 27: proto.AddMemberRequest
	(*AddMemberReply)(nil),       // 28: proto.AddMemberReply
	(*Memberchange)(nil),         // 29: proto.Memberchange
	(*DeleteMemberRequest)(nil),  // 30: proto.DeleteMemberRequest
	(*DeleteMemberReply)(nil),    // 31: proto.DeleteMemberReply
	(*RequestVoteArgs)(nil),      // 32: proto.RequestVoteArgs
	(*RequestVoteReply)(nil),     // 33: proto.RequestVoteReply
	(*LogEntry)(nil),             // 34: proto.LogEntry
	(*HeartbeatArgs)(nil),        // 35: proto.HeartbeatArgs
	(*HeartbeatReply)(nil),       // 36: proto.HeartbeatReply
	(*InstallSnapshotArgs)(nil),  // 37: proto.InstallSnapshotArgs
	(*InstallSnapshotReply)(nil), // 38: proto.InstallSnapshotReply
	(*Op)(nil),                   // 39: proto.Op
}
var file_proto_service_proto_depIdxs = []int32{
	1,  // 0: proto.Compare.compare_type:type_name -> proto.CompareType
	2,  // 1: proto.TxnRequest.compare:type_name -> proto.Compare
	24, // 2: proto.TxnRequest.success:type_name -> proto.Entry
	24, // 3: proto.TxnRequest.failed:type_name -> proto.Entry
	0,  // 4: proto.TxnReply.error:type_name -> proto.ErrorType
	14, // 5: proto.TxnReply.results:type_name -> proto.KeyValue
	0,  // 6: proto.LockReply.error:type_name -> proto.ErrorType
	0,  // 7: proto.UnlockReply.error:type_name -> proto.ErrorType
	0,  // 8: proto.WatchReply.err:type_name -> proto.ErrorType
	0,  // 9: proto.PutReply.error:type_name -> proto.ErrorType
	14, // 10: proto.GetReply.kvs:type_name -> proto.KeyValue
	0,  // 11: proto.GetReply.error:type_name -> proto.ErrorType
	0,  // 12: proto.DeleteReply.error:type_name -> proto.ErrorType
	0,  // 13: proto.CompactReply.error:type_name -> proto.ErrorType
	0,  // 14: proto.KeepAliveReply.error:type_name -> proto.ErrorType
	0,  // 15: proto.GrantReply.error:type_name -> proto.ErrorType
	24, // 16: proto.BatchRequest.entries:type_name -> proto.Entry
	0,  // 17: proto.BatchReply.error:type_name -> proto.ErrorType
	0,  // 18: proto.AddMemberReply.error:type_name -> proto.ErrorType
	0,  // 19: proto.DeleteMemberReply.error:type_name -> proto.ErrorType
	34, // 20: proto.HeartbeatArgs.entries:type_name -> proto.LogEntry
	24, // 21: proto.Op.entries:type_name -> proto.Entry
	29, // 22: proto.Op.member_change:type_name -> proto.Memberchange
	2,  // 23: proto.Op.compares:type_name -> proto.Compare
	24, // 24: proto.Op.success_entries:type_name -> proto.Entry
	24, // 25: proto.Op.failed_entries:type_name -> proto.Entry
	11, // 26: proto.Kv.Put:input_type -> proto.PutRequest
	13, // 27: proto.Kv.Get:input_type -> proto.GetRequest
	16, // 28: proto.Kv.Delete:input_type -> proto.DeleteRequest
	25, // 29: proto.Kv.Batch:input_type -> proto.BatchRequest
	9,  // 30: proto.Kv.Watch:input_type -> proto.WatchRequest
	18, // 31: proto.Kv.Compact:input_type -> proto.CompactRequest
	20, // 32: proto.Kv.KeepAlive:input_type -> proto.KeepAliveRequest
	22, // 33: proto.Kv.Grant:input_type -> proto.GrantRequest
	27, // 34: proto.Kv.AddMember:input_type -> proto.AddMemberRequest
	30, // 35: proto.Kv.DeleteMember:input_type -> proto.DeleteMemberRequest
	3,  // 36: proto.Kv.Txn:input_type -> proto.TxnRequest
	5,  // 37: proto.Kv.Lock:input_type -> proto.LockRequest
	7,  // 38: proto.Kv.Unlock:input_type -> proto.UnlockRequest
	32, // 39: proto.Raft.RequestVote:input_type -> proto.RequestVoteArgs
	35, // 40: proto.Raft.AppendEntries:input_type -> proto.HeartbeatArgs
	37, // 41: proto.Raft.InstallSnapshot:input_type -> proto.InstallSnapshotArgs
	12, // 42: proto.Kv.Put:output_type -> proto.PutReply
	15, // 43: proto.Kv.Get:output_type -> proto.GetReply
	17, // 44: proto.Kv.Delete:output_type -> proto.DeleteReply
	26, // 45: proto.Kv.Batch:output_type -> proto.BatchReply
	10, // 46: proto.Kv.Watch:output_type -> proto.WatchReply
	19, // 47: proto.Kv.Compact:output_type -> proto.CompactReply
	21, // 48: proto.Kv.KeepAlive:output_type -> proto.KeepAliveReply
	23, // 49: proto.Kv.Grant:output_type -> proto.GrantReply
	28, // 50: proto.Kv.AddMember:output_type -> proto.AddMemberReply
	31, // 51: proto.Kv.DeleteMember:output_type -> proto.DeleteMemberReply
	4,  // 52: proto.Kv.Txn:output_type -> proto.TxnReply
	6,  // 53: proto.Kv.Lock:output_type -> proto.LockReply
	8,  // 54: proto.Kv.Unlock:output_type -> proto.UnlockReply
	33, // 55: proto.Raft.RequestVote:output_type -> proto.RequestVoteReply
	36, // 56: proto.Raft.AppendEntries:output_type -> proto.HeartbeatReply
	38, // 57: proto.Raft.InstallSnapshot:output_type -> proto.InstallSnapshotReply
	42, // [42:58] is the sub-list for method output_type
	26, // [26:42] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_proto_service_proto_init() }
func file_proto_service_proto_init() {
	if File_proto_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_service_proto_rawDesc), len(file_proto_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_service_proto_goTypes,
		DependencyIndexes: file_proto_service_proto_depIdxs,
		EnumInfos:         file_proto_service_proto_enumTypes,
		MessageInfos:      file_proto_service_proto_msgTypes,
	}.Build()
	File_proto_service_proto = out.File
	file_proto_service_proto_goTypes = nil
	file_proto_service_proto_depIdxs = nil
}
